# Generated by Django 4.2.7 on 2023-11-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='tc',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
