# Generated by Django 4.2.7 on 2023-11-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='abc@gmail.com', max_length=10),
            preserve_default=False,
        ),
    ]
