# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\Create_exam_questions_admin_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Add_questionButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add_questionButton.setGeometry(QtCore.QRect(20, 50, 101, 51))
        self.Add_questionButton.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF; /* Button background color */\n"
"    border: none; /* Remove the button border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    color: #FFFFFF; /* Text color */\n"
"    font-size: 10px; /* Font size */\n"
"    padding: 10px 20px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker background color on hover */\n"
"}\n"
"")
        self.Add_questionButton.setObjectName("Add_questionButton")
        self.Add_radioButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add_radioButton.setGeometry(QtCore.QRect(20, 170, 101, 51))
        self.Add_radioButton.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF; /* Button background color */\n"
"    border: none; /* Remove the button border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    color: #FFFFFF; /* Text color */\n"
"    font-size: 10\n"
"px; /* Font size */\n"
"    padding: 10px 20px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker background color on hover */\n"
"}\n"
"")
        self.Add_radioButton.setObjectName("Add_radioButton")
        self.Add_choicesButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add_choicesButton.setGeometry(QtCore.QRect(20, 110, 101, 51))
        self.Add_choicesButton.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF; /* Button background color */\n"
"    border: none; /* Remove the button border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    color: #FFFFFF; /* Text color */\n"
"    font-size: 10px; /* Font size */\n"
"    padding: 10px 20px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker background color on hover */\n"
"}\n"
"")
        self.Add_choicesButton.setObjectName("Add_choicesButton")
        self.Add_imageButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add_imageButton.setGeometry(QtCore.QRect(20, 290, 101, 51))
        self.Add_imageButton.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF; /* Button background color */\n"
"    border: none; /* Remove the button border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    color: #FFFFFF; /* Text color */\n"
"    font-size: 10px; /* Font size */\n"
"    padding: 10px 20px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker background color on hover */\n"
"}\n"
"")
        self.Add_imageButton.setObjectName("Add_imageButton")
        self.Add_exceltableButton = QtWidgets.QPushButton(self.centralwidget)
        self.Add_exceltableButton.setGeometry(QtCore.QRect(20, 230, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.Add_exceltableButton.setFont(font)
        self.Add_exceltableButton.setStyleSheet("QPushButton {\n"
"    background-color: #007AFF; /* Button background color */\n"
"    border: none; /* Remove the button border */\n"
"    border-radius: 10px; /* Rounded corners */\n"
"    color: #FFFFFF; /* Text color */\n"
"    font-size: 10px; /* Font size */\n"
"    padding: 10px 20px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #0056b3; /* Darker background color on hover */\n"
"}\n"
"")
        self.Add_exceltableButton.setObjectName("Add_exceltableButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(160, 50, 341, 51))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f0f0; /* Background color */\n"
"    border: 1px solid #d0d0d0; /* Border color */\n"
"    border-radius: 8px; /* Rounded corners */\n"
"    padding: 8px; /* Padding inside the input field */\n"
"    font-size: 16px; /* Font size */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #007AFF; /* Border color when focused */\n"
"    background-color: #ffffff; /* Background color when focused */\n"
"}\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.OPTION_1 = QtWidgets.QRadioButton(self.centralwidget)
        self.OPTION_1.setGeometry(QtCore.QRect(160, 320, 101, 41))
        self.OPTION_1.setStyleSheet("QRadioButton {\n"
"    border: 2px solid #007AFF; /* Outer circle border color */\n"
"    border-radius: 12px; /* Rounded shape */\n"
"    padding: 4px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px; /* Size of the inner circle */\n"
"    height: 16px;\n"
"    border: 2px solid #007AFF; /* Inner circle border color */\n"
"    border-radius: 8px; /* Rounded shape for the inner circle */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #007AFF; /* Fill color when selected */\n"
"}\n"
"")
        self.OPTION_1.setObjectName("OPTION_1")
        self.OPTION_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.OPTION_2.setGeometry(QtCore.QRect(160, 370, 101, 41))
        self.OPTION_2.setStyleSheet("QRadioButton {\n"
"    border: 2px solid #007AFF; /* Outer circle border color */\n"
"    border-radius: 12px; /* Rounded shape */\n"
"    padding: 4px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px; /* Size of the inner circle */\n"
"    height: 16px;\n"
"    border: 2px solid #007AFF; /* Inner circle border color */\n"
"    border-radius: 8px; /* Rounded shape for the inner circle */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #007AFF; /* Fill color when selected */\n"
"}\n"
"")
        self.OPTION_2.setObjectName("OPTION_2")
        self.OPTION_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.OPTION_3.setGeometry(QtCore.QRect(160, 420, 101, 41))
        self.OPTION_3.setStyleSheet("QRadioButton {\n"
"    border: 2px solid #007AFF; /* Outer circle border color */\n"
"    border-radius: 12px; /* Rounded shape */\n"
"    padding: 4px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px; /* Size of the inner circle */\n"
"    height: 16px;\n"
"    border: 2px solid #007AFF; /* Inner circle border color */\n"
"    border-radius: 8px; /* Rounded shape for the inner circle */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #007AFF; /* Fill color when selected */\n"
"}\n"
"")
        self.OPTION_3.setObjectName("OPTION_3")
        self.OPTION_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.OPTION_4.setGeometry(QtCore.QRect(160, 470, 101, 41))
        self.OPTION_4.setStyleSheet("QRadioButton {\n"
"    border: 2px solid #007AFF; /* Outer circle border color */\n"
"    border-radius: 12px; /* Rounded shape */\n"
"    padding: 4px; /* Adjust padding as needed */\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 16px; /* Size of the inner circle */\n"
"    height: 16px;\n"
"    border: 2px solid #007AFF; /* Inner circle border color */\n"
"    border-radius: 8px; /* Rounded shape for the inner circle */\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    background-color: #007AFF; /* Fill color when selected */\n"
"}\n"
"")
        self.OPTION_4.setObjectName("OPTION_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 110, 81, 21))
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(160, 140, 361, 131))
        self.widget.setStyleSheet("background-color: #ffffff; /* Background color */\n"
"border: 1px solid #d1d1d1; /* Border color */\n"
"border-radius: 10px; /* Rounded corners */\n"
"")
        self.widget.setObjectName("widget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Add_questionButton.setText(_translate("MainWindow", "Add Question"))
        self.Add_radioButton.setText(_translate("MainWindow", "Radio Button"))
        self.Add_choicesButton.setText(_translate("MainWindow", "Choices"))
        self.Add_imageButton.setText(_translate("MainWindow", "Image"))
        self.Add_exceltableButton.setText(_translate("MainWindow", "Table"))
        self.OPTION_1.setText(_translate("MainWindow", "Option_1"))
        self.OPTION_2.setText(_translate("MainWindow", "Option_2"))
        self.OPTION_3.setText(_translate("MainWindow", "Option_3"))
        self.OPTION_4.setText(_translate("MainWindow", "Option_4"))
        self.label.setText(_translate("MainWindow", "Diagram"))
        self.label_2.setText(_translate("MainWindow", "Create Exam"))
