# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\question_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(373, 450)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(161, 41))
        self.label.setMaximumSize(QtCore.QSize(161, 41))
        self.label.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMinimumSize(QtCore.QSize(161, 41))
        self.label_2.setMaximumSize(QtCore.QSize(161, 41))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(361, 251))
        self.widget.setStyleSheet("background-color: rgb(133, 255, 194);")
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        # self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        # self.pushButton_3.setMinimumSize(QtCore.QSize(31, 31))
        # self.pushButton_3.setMaximumSize(QtCore.QSize(31, 31))
        # self.pushButton_3.setObjectName("pushButton_3")
        # self.gridLayout.addWidget(self.pushButton_3, 0, 1, 1, 1)
        # self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        # self.pushButton_2.setMinimumSize(QtCore.QSize(31, 31))
        # self.pushButton_2.setMaximumSize(QtCore.QSize(31, 31))
        # self.pushButton_2.setStyleSheet("background-color: rgb(255, 162, 119);")
        # self.pushButton_2.setObjectName("pushButton_2")
        # self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        # self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        # self.pushButton_5.setMinimumSize(QtCore.QSize(31, 31))
        # self.pushButton_5.setMaximumSize(QtCore.QSize(31, 31))
        # self.pushButton_5.setObjectName("pushButton_5")
        # self.gridLayout.addWidget(self.pushButton_5, 0, 3, 1, 1)
        # self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        # self.pushButton_4.setMinimumSize(QtCore.QSize(31, 31))
        # self.pushButton_4.setMaximumSize(QtCore.QSize(31, 31))
        # self.pushButton_4.setObjectName("pushButton_4")
        # self.gridLayout.addWidget(self.pushButton_4, 0, 2, 1, 1)
        # self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        # self.pushButton_6.setMinimumSize(QtCore.QSize(31, 31))
        # self.pushButton_6.setMaximumSize(QtCore.QSize(31, 31))
        # self.pushButton_6.setObjectName("pushButton_6")
        # self.gridLayout.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem2 = QtWidgets.QSpacerItem(90, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalScrollBar = QtWidgets.QScrollBar(self.widget)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.horizontalLayout_3.addWidget(self.verticalScrollBar)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(101, 31))
        self.pushButton.setMaximumSize(QtCore.QSize(101, 31))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 373, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Exam Name"))
        self.label_2.setText(_translate("MainWindow", "Time : 00:00:00"))
        # self.pushButton_3.setText(_translate("MainWindow", "2"))
        # self.pushButton_2.setText(_translate("MainWindow", "1"))
        # self.pushButton_5.setText(_translate("MainWindow", "4"))
        # self.pushButton_4.setText(_translate("MainWindow", "3"))
        # self.pushButton_6.setText(_translate("MainWindow", "5"))
        self.pushButton.setText(_translate("MainWindow", "Submit"))


class QuestionWindow(QtWidgets.QMainWindow,Ui_MainWindow):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)
        
        # self.pushButton.clicked.connect(self.get_email_password)
    
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QMainWindow()
    ui = QuestionWindow()
    ui.show()
    sys.exit(app.exec_())