# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\question_atempting_screen_candidate_view.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class question_attmpting_page(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(993, 770)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.questionPanel = QtWidgets.QTextEdit(self.centralwidget)
        self.questionPanel.setGeometry(QtCore.QRect(10, 110, 441, 71))
        self.questionPanel.setObjectName("questionPanel")
        self.option1 = QtWidgets.QRadioButton(self.centralwidget)
        self.option1.setGeometry(QtCore.QRect(30, 270, 82, 17))
        self.option1.setObjectName("option1")
        self.option3 = QtWidgets.QRadioButton(self.centralwidget)
        self.option3.setGeometry(QtCore.QRect(30, 300, 82, 17))
        self.option3.setObjectName("option3")
        self.option3_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.option3_2.setGeometry(QtCore.QRect(30, 330, 82, 17))
        self.option3_2.setObjectName("option3_2")
        self.option4 = QtWidgets.QRadioButton(self.centralwidget)
        self.option4.setGeometry(QtCore.QRect(30, 360, 82, 17))
        self.option4.setObjectName("option4")
        self.examdetails = QtWidgets.QTextEdit(self.centralwidget)
        self.examdetails.setGeometry(QtCore.QRect(10, 0, 971, 101))
        self.examdetails.setObjectName("examdetails")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(0, 60, 251, 41))
        self.textEdit_3.setStyleSheet("\n"
"background-color: rgb(255, 0, 0);")
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(250, 60, 251, 41))
        self.textEdit_4.setStyleSheet("background-color: rgb(180, 255, 247);")
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(500, 60, 251, 41))
        self.textEdit_5.setStyleSheet("background-color: rgb(204, 0, 255);")
        self.textEdit_5.setObjectName("textEdit_5")
        self.panel = QtWidgets.QTextEdit(self.centralwidget)
        self.panel.setGeometry(QtCore.QRect(760, 130, 221, 481))
        self.panel.setObjectName("panel")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(780, 170, 41, 20))
        self.plainTextEdit.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"background-color: rgb(47, 255, 44);")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.panelattemptedquestions = QtWidgets.QTextEdit(self.centralwidget)
        self.panelattemptedquestions.setGeometry(QtCore.QRect(770, 140, 111, 21))
        self.panelattemptedquestions.setObjectName("panelattemptedquestions")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(830, 170, 41, 20))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(880, 170, 41, 20))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_4.setGeometry(QtCore.QRect(930, 170, 41, 20))
        self.plainTextEdit_4.setObjectName("plainTextEdit_4")
        self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_5.setGeometry(QtCore.QRect(780, 220, 41, 20))
        self.plainTextEdit_5.setObjectName("plainTextEdit_5")
        self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_6.setGeometry(QtCore.QRect(830, 220, 41, 20))
        self.plainTextEdit_6.setObjectName("plainTextEdit_6")
        self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_7.setGeometry(QtCore.QRect(880, 220, 41, 20))
        self.plainTextEdit_7.setObjectName("plainTextEdit_7")
        self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_8.setGeometry(QtCore.QRect(930, 220, 41, 20))
        self.plainTextEdit_8.setObjectName("plainTextEdit_8")
        self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_9.setGeometry(QtCore.QRect(780, 270, 41, 20))
        self.plainTextEdit_9.setObjectName("plainTextEdit_9")
        self.plainTextEdit_10 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_10.setGeometry(QtCore.QRect(830, 270, 41, 21))
        self.plainTextEdit_10.setObjectName("plainTextEdit_10")
        self.plainTextEdit_11 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_11.setGeometry(QtCore.QRect(880, 270, 41, 20))
        self.plainTextEdit_11.setObjectName("plainTextEdit_11")
        self.plainTextEdit_12 = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_12.setGeometry(QtCore.QRect(930, 270, 41, 20))
        self.plainTextEdit_12.setObjectName("plainTextEdit_12")
        self.bottompanelbox = QtWidgets.QTextEdit(self.centralwidget)
        self.bottompanelbox.setGeometry(QtCore.QRect(10, 650, 991, 81))
        self.bottompanelbox.setObjectName("bottompanelbox")
        self.previous = QtWidgets.QPushButton(self.centralwidget)
        self.previous.setGeometry(QtCore.QRect(20, 660, 75, 23))
        self.previous.setObjectName("previous")
        self.savenextbutton = QtWidgets.QPushButton(self.centralwidget)
        self.savenextbutton.setGeometry(QtCore.QRect(270, 660, 75, 23))
        self.savenextbutton.setObjectName("savenextbutton")
        self.next = QtWidgets.QPushButton(self.centralwidget)
        self.next.setGeometry(QtCore.QRect(100, 660, 75, 23))
        self.next.setObjectName("next")
        self.mark = QtWidgets.QPushButton(self.centralwidget)
        self.mark.setGeometry(QtCore.QRect(190, 660, 75, 23))
        self.mark.setObjectName("mark")
        self.submitbutton = QtWidgets.QPushButton(self.centralwidget)
        self.submitbutton.setGeometry(QtCore.QRect(840, 580, 75, 23))
        self.submitbutton.setObjectName("submitbutton")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(870, 700, 111, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(870, 110, 111, 20))
        self.label.setObjectName("label")
        self.diagrmbox = QtWidgets.QTextEdit(self.centralwidget)
        self.diagrmbox.setGeometry(QtCore.QRect(30, 190, 104, 71))
        self.diagrmbox.setObjectName("diagrmbox")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(780, 80, 191, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(880, 0, 71, 71))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(".\\uis\\../../Users/Lenovo/Downloads/WhatsApp Image 2023-09-10 at 12.35.47 PM (1).jpg"))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 993, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.questionPanel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Question 1 </p></body></html>"))
        self.option1.setText(_translate("MainWindow", "option 1"))
        self.option3.setText(_translate("MainWindow", "option2 "))
        self.option3_2.setText(_translate("MainWindow", "option3 "))
        self.option4.setText(_translate("MainWindow", "option 4"))
        self.examdetails.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Aptitude test </span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#090909;\">Quantitative aptitude</span></p></body></html>"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">verbal ability</p></body></html>"))
        self.textEdit_5.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">verbal reasoning</p></body></html>"))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "Q1"))
        self.panelattemptedquestions.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Questions </p></body></html>"))
        self.plainTextEdit_2.setPlainText(_translate("MainWindow", "Q2"))
        self.plainTextEdit_3.setPlainText(_translate("MainWindow", "Q3"))
        self.plainTextEdit_4.setPlainText(_translate("MainWindow", "Q4\n"
""))
        self.plainTextEdit_5.setPlainText(_translate("MainWindow", "Q5"))
        self.plainTextEdit_6.setPlainText(_translate("MainWindow", "Q6"))
        self.plainTextEdit_7.setPlainText(_translate("MainWindow", "Q7"))
        self.plainTextEdit_8.setPlainText(_translate("MainWindow", "Q8\n"
""))
        self.plainTextEdit_9.setPlainText(_translate("MainWindow", "Q9"))
        self.plainTextEdit_10.setPlainText(_translate("MainWindow", "Q10"))
        self.plainTextEdit_11.setPlainText(_translate("MainWindow", "Q11"))
        self.plainTextEdit_12.setPlainText(_translate("MainWindow", "Q12"))
        self.previous.setText(_translate("MainWindow", "Previous"))
        self.savenextbutton.setText(_translate("MainWindow", "save& next"))
        self.next.setText(_translate("MainWindow", "next"))
        self.mark.setText(_translate("MainWindow", "Mark"))
        self.submitbutton.setText(_translate("MainWindow", "submit"))
        self.pushButton_6.setText(_translate("MainWindow", "Read instruction"))
        self.label.setText(_translate("MainWindow", "Time left-00:00:00"))
        self.diagrmbox.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">diagram</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Time left for entire exam-00:00:00"))


class Question_attempting_window(QtWidgets.QMainWindow,question_attmpting_page):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setupUi(self)