# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\uis\warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(246, 72)
        Dialog.setMinimumSize(QtCore.QSize(246, 72))
        Dialog.setMaximumSize(QtCore.QSize(246, 72))
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(180, 50, 56, 17))
        self.pushButton.setMinimumSize(QtCore.QSize(56, 17))
        self.pushButton.setMaximumSize(QtCore.QSize(56, 17))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 10, 101, 16))
        self.label.setStyleSheet('font: 10pt "MS Shell Dlg 2";')
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 10, 51, 51))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("image: url(:/images/pngwing.com.png);")
        self.widget.setObjectName("widget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "OK"))
        self.label.setText(_translate("Dialog", "Warning !"))


import resources_rc


class WarningWindow(QtWidgets.QMainWindow, Ui_Dialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        # self.selected_answer = None
        self.setupUi(self)
        self.pushButton.clicked.connect(self.close_widget)

    def close_widget(self):
        self.close()


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QMainWindow()
    ui = WarningWindow()
    ui.show()
    sys.exit(app.exec_())
