# Generated by Django 4.2.7 on 2023-11-06 07:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_student_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='organisation',
            field=models.ForeignKey(default=datetime.datetime(2023, 11, 6, 7, 38, 13, 114329, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questions',
            name='exam',
            field=models.ForeignKey(default=datetime.datetime(2023, 11, 6, 7, 38, 20, 975645, tzinfo=datetime.timezone.utc), on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Warning_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.answeroptions')),
            ],
        ),
    ]
