# Generated by Django 4.2.7 on 2024-01-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exam", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="duration",
            field=models.IntegerField(default=60),
        ),
    ]
